overblog_graphql:
    definitions:
        schema:
            query: Query
            # mutation: Mutation
        mappings:
            types:
                - type: attribute
                  dir: "%kernel.project_dir%/src"
                  suffix: ~
    batching_method: "apollo"
    services:
        promise_adapter: "webonyx_graphql.sync_promise_adapter"