version: "3.7"

services:
  app_recipe:
    build:
      args:
        - SYMFONY_ENV=staging
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - symfony

  node:
    build:
      context: ./docker
      dockerfile: Dockerfile-node
    command: bash -c "yarn && yarn dev && tail -f /dev/null"
    volumes:
      - ./:/var/www/project
    networks:
      - symfony

networks:
  symfony:
  traefik:
    external: true

volumes:
  persistent:
